### ISSUE TITLE
Service maxes out number of open files

### ISSUE THREAD

**Issue by wlymanambry** [biocommons/seqrepo-rest-service#14] opened 2023-08-23 16:15 UTC
This service was working great for me for a couple of days but then it maxes out the OS allowable files open at the same time and fails. 

Gives a Failed to open FASTA index ... "Too many open files"

A lsof | wc -l shows ->  65,863 files, a huge number of db.sqlite3 as well as individual fasta files. 

Is there a workaround for this?

**Comment by theferrit32** [comment] 2023-08-24 15:55
Hi @wlymanambry can you give a sense of what kind of workload you are running? Do you have a `seqrepo-rest-service` process running continuously over a couple days? Are you sending a lot of requests in rapid succession?

**Comment by wlymanambry** [comment] 2023-08-24 15:57
I have a dataset coming back from a lambda function that is being kept warm so I am hitting seq repo 100 times every 5 minutes as part of this. The seqrepo-rest-service is running continuously. (should this not be the case?)

**Comment by theferrit32** [comment] 2023-08-24 16:05
It should be fine to leave running continuously. I'm just trying to guess whether the issue you're seeing might be resolved by the eventual fixes here:

https://github.com/biocommons/biocommons.seqrepo/issues/112#issuecomment-1611674050

**Comment by wlymanambry** [comment] 2023-08-24 16:10
Reading over that thread you linked. It looks promising.

**Comment by davmlaw** [comment] 2023-08-25 05:24
"Too many open files" is usually from the operating system. Check ```ulimit -n```

while waiting for the fix above, you could temporarily adjust this via  /etc/security/limits.conf

**Comment by wlymanambry** [comment] 2023-08-25 14:06
Thanks. Are there any performance considerations for this? It will end up having hundreds of thousands of open files after a week or so.

**Comment by davmlaw** [comment] 2023-08-27 07:28
I don't know... I think the overhead per file isn't much, and there are only like 0.5M Refseq transcripts.

It's probably fine on modern machines, maybe check RAM after a week.

**Comment by reece** [comment] 2023-09-07 14:34
This appears to be a duplicate of #12. I'm going to close and we can continue discussion there.

**Closed as completed by reece** 2023-09-07 14:34 UTC

**Comment by reece** [comment] 2023-09-07 14:53
@wlymanambry 

> Thanks. Are there any performance considerations for this? It will end up having hundreds of thousands of open files after a week or so.

Increasing the fd limit will help, but only delay the failure. You won't have enough fds to stave off the issue forever, unfortunately.

**Comment by theferrit32** [comment] 2023-11-14 23:15
@wlymanambry Can you try using the recent tag `0.2.2` in this repo and see if resolves the issue you were seeing? This is also available in pypi `seqrepo-rest-service==0.2.2` and in dockerhub `biocommons/seqrepo-rest-service:0.2.2`

**Comment by wlymanambry** [comment] 2023-11-14 23:48
> @wlymanambry Can you try using the recent tag `0.2.2` in this repo and see if resolves the issue you were seeing? This is also available in pypi `seqrepo-rest-service==0.2.2` and in dockerhub `biocommons/seqrepo-rest-service:0.2.2`

Will do as soon as I get a chance. Thanks!

**Comment by wlymanambry** [comment] 2023-12-12 22:08
Sorry for the lengthy delay. After pulling this version it appears I'm still ending up with open files but at a much slower rate: 
![image](https://github.com/biocommons/seqrepo-rest-service/assets/87200828/603697f7-f683-4e6e-beac-48f6b51303d4)

**Comment by wlymanambry** [comment] 2023-12-27 20:38
Update on this. I've been hitting the service now for several weeks and it looks like the number of open files is staying constant.
